# Generated by Django 5.1.2 on 2024-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not sure', 'Not sure'), ('Queer', 'Queer'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
            ],
        ),
    ]
