# Generated by Django 5.1.2 on 2024-10-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registration_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not sure', 'Not sure'), ('Queer', 'Queer'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(max_length=20),
        ),
    ]
